### ISSUE TITLE
JSON export format fix?

### ISSUE THREAD

**Issue by Brian151** [gmariani/minerva#70]
Is it possible to export using the 'correct' data types?

I exported a fairly complex SOL as JSON...
The arrays are all objects with properties defined as "1":value,"2":value, etc...
The booleans are the numbers 0 or 1

Is it possible to export them more like:
{
"object" : {},
"array" : [0,1,2,3],
"bool" : false,
"bool2" : true
}

, instead?

It's not a huge issue, but it's kind of annoying
Also, that array one, in particular, could cause problems trying to use the export in a program

**Comment by gmariani** [comment]
It's been a while since I've looked at the program, but what I recall is that SOL stores data in a compact fashion. So instead of a true boolean (true/false) it may store it as a 1 or 0, but not specify what the original type was. Again, i may be wrong, it's been a while. But I do remember that the types were hard to assume since they get lost in translation. Do you have a sample file I could test with?

**Comment by gmariani** [comment]
This should be fixed in 4.2.0

**Comment by Brian151** [comment]
sry for delayed response
I do recall reading in the AMF specs booleans have two types, so it is detectable

I'll take a look at the app again later
Need to sleep now, but I wanna clear some tabs out, first

**Comment by gmariani** [comment]
No rush, i haven't pushed the 4.2.0 version out yet. I'm changing my build process but once i get that wrapped up it will be released.

**Comment by gmariani** [comment]
4.2.0 is now live
