### ISSUE TITLE
Unable to save（Uncaught RangeError: Too many elements in SOL file to process in your current browser.）

### ISSUE THREAD

**Issue by CoolLby** [gmariani/minerva#79]
### Problem description 
- When the modification file is complete, click Save, will report the error.
### Browser information
- Google Chrome is the latest version
Version 68.0.3440.84 (formal version)
### Error information
> ### Error
>
> Error saving file:
>  
> Uncaught RangeError: Too many elements in SOL file to process in your current browser.
> (https://mariani.life/projects/minerva/js/parsers/SOLWriterWorker.js:1)

### Error screenshots and error files
![tim 20180804213925](https://user-images.githubusercontent.com/38807139/43677135-7c673936-982f-11e8-9626-6e34d4ffe5b2.png)

[JY1.zip](https://github.com/gmariani/minerva/files/2259517/JY1.zip)

Looking forward to your reply！

**Comment by gmariani** [comment]
Unfortunately this appears to be the same issue I thought was resolved with recent versions of Chrome. If you try the same file in Firefox it will work just fine, but Chrome (specifically x64 version) has a cap.

https://bugs.chromium.org/p/chromium/issues/detail?id=252492

I'll dig into it a big more to confirm this is the issue, but this is exactly what I encountered a long while back. They said they fixed it in Chrome 56+, but running v68 here and still erroring.

**Comment by gmariani** [comment]
Yes, it appears it's still a Chrome issue. The limit was incorrectly set to 65kb of data can be saved. Your file is 100kb, if I manipulate it to become less than 65kb, it saves without issue. But at 68kb, it errors. Unfortunately the only solution is for Chrome to fix the issue or use Firefox =/

**Comment by Ignis34Rus** [comment]
``` javascript
// Convert to an array to escape worker unphased
var arrReturn = new Int8Array(ba._buffer.slice(0, ba.position));
try {
	arrReturn = Array.apply([], arrReturn);
} catch (err) {
	if (
		err.name == 'RangeError' &&
		err.message == 'Maximum call stack size exceeded'
	) {
		throw RangeError(
			'Too many elements in SOL file to process in your current browser, please try Firefox.'
		);
	} else {
		throw err;
	}
}
postMessage({ data: arrReturn });
```
maybe I don't understand something, but is this block of code in _SOLWriterWorker.js_ necessary?
``` javascript
// Convert to an array to escape worker unphased
var arrReturn = new Int8Array(ba._buffer.slice(0, ba.position));
postMessage({ data: arrReturn });
```
this works (at least in Chrome) just fine

**Comment by CoolLby** [comment]
Ok, thank you for your reply, which is very helpful to me！ @gmariani

**Comment by gmariani** [comment]
Ok, so I tried it out and it does indeed fix that issue and it SEEMS with no ill-effect. I'll make that change and after further testing probably push this out at 4.3.2. Thanks for the suggestion @Ignis34Rus !

Testing with the JY1 file, Chrome and Edge on 4.3.1 could not export it, only Firefox could. But on 4.3.2, Chrome, Edge and Firefox could export successfully. Testing with the file from #78 , a much larger file at 265k, on 4.3.1 only Firefox could export it and the file was 339k. On 4.3.2, Chrome, Firefox and Edge can all export it, but the file size is 813k across all three. The file size variation is due to minerva not fulling leveraging object references. But I might do that after this since 78 fixed the reference reading and this would fix the exporting stack overflow.

**Comment by gmariani** [comment]
This has been pushed live, let me know if you run into any issues
