### ISSUE TITLE
Error when trying to open .sol

### ISSUE THREAD

**Issue by Garzhad** [gmariani/minerva#81]
Error

Error reading file:
NetworkError: Failed to load worker script at "http://cdn.coursevector.com/minerva/4.1.2/js/lib/ByteArray.js"
(http://apps.coursevector.com/minerva/js/parsers/SOLReaderWorker.js:1)

Not sure what this means really but it prevents editting saves.

**Comment by gmariani** [comment]
Try again? Not sure what to tell you. Maybe it's a caching issue, clear your browser cache. I've been using it regularly the past few days without issue.
Looks like you're using a really old version of it though, I'm on 4.3.1 and it's looking for 4.1.2 which is long gone.
Don't know what browser you're using, but clear out any application caching from the service worker might help.

**Comment by gmariani** [comment]
The web version of .minerva does work offline if you use a modern browser.

As for the legacy version (Adobe AIR), the issue was that Adobe requires you to package the file with a signed certificate that typically expired every 2 years. Which meant I had to repackage it regardless if there were any changes or it would fail to install. Maybe a month or so ago I found out how to repackage it with a certificate that lasts for any number of years. So i have a repackaged version with a 50 year certificate. I updated the link in the About window on .minerva but forgot to update the webpage. Here is the link for the re-signed version: https://mariani-cdn.s3.amazonaws.com/download/Minerva-3-5-0-resigned.air
